config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'about', to: 'about#index', as: 'about'
  root to: 'products#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :users, only: [:new, :create]
  
  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  
  resources :orders, only: [:create, :show]
  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true
    validates :password, presence: true
  end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
  end
  

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
    def index
      @categories = Category.all
    end
  
    def new
      @category = Category.new
    end
  
    def create
      @category = Category.new(category_params)
  
      if @category.save
        redirect_to [:admin, :categories], notice: 'Category created!'
      else
        render :new
      end
    end
  
    private
  
    def category_params
      params.require(:category).permit(:name)
    end
  end
  

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @product_count = Product.all.count
    @category_count = Category.all.count
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: "Jungle", password: "book"
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path unless logged_in?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

  def add_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, +1)

    redirect_back fallback_location: root_path
  end

  def remove_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, -1)

    redirect_back fallback_location: root_path
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_subtotal_cents,
      description: "Khurram Virani's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end
    order.save!
    order
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    # @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
    )
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/about/index.html.erb
<section class="about-us">
  <h2>About Us</h2>
  <p>
    Looking for a way to add some life to your home? Look no further than our online plant shop! We have a wide variety of beautiful plants and flowers, as well as all the accessories you need to keep them healthy and happy. Plus, our prices are unbeatable! So what are you waiting for?
  </p>
  <p>
    At our online plant shop, we only sell the highest quality plants and flowers. We source our products from reputable growers and nurseries, so you can be sure you're getting a healthy, beautiful plant. Plus, ordering is quick and easy! We offer free shipping on all orders over $50, so it's easy to get the plants you want without breaking the bank.
  </p>
  <p>
    We have a wide variety of plants and flowers available for purchase on our website. Whether you're looking for something small and delicate or big and bold, we have the perfect plant for you. We also carry a selection of accessories, including potting soil, pots and containers, watering cans, and more.
  </p>
</section>

app/views/admin/categories/index.html.erb
<section class="admin-categories-index">

  <header class="page-header">
    <h1>Admin &raquo; All Categories</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Category', [:new, :admin, :category], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default categories">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Category</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %> 
          <tr>
            <td><%= category.name %></td>
          </tr>
        <% end %>    
      </tbody>
    </table>

  </div>

</section>

app/views/admin/categories/new.html.erb
<section class="admin-categories-new">

  <header class="page-header">
    <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @category] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/products/_product.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= product.category.name %>
  </td>
  <td>
    <%= humanized_money_with_symbol product.price %>
  </td>
  <td>
    <%= product.quantity %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, product], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/products/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Products</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Qty Remaining</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/products/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Product</h1>
  </header>

  <div class="well">
    <%= link_to 'All Products', [:admin, :products], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @product] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.select :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name), { include_blank: true }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :quantity %>
          <%= form.number_field :quantity, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price, class: 'form-control' %>
        </div>



        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image %>
        </div>

        <%= form.submit 'Create Product', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/categories/show.html.erb
<section class="categories-show">

  <header class="page-header">
    <h1>
      <%= @category.name %>
      <small>(<%= pluralize @products.size, 'product' %>)</small>
    </h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/orders/_item.html.erb
<!-- app/views/orders/_item.html.erb -->

<div class="line-item">
  <div class="item-details">
    <h4><%= item.product.name %></h4>
    <%= image_tag item.product.image.thumb.url, alt: item.product.name, class: "img-fluid" %>
    <p class="description"><%= item.product.description %></p>
  </div>

  <div class="item-metadata">
    <div class="metadata">
      <h4>Quantity</h4>
      <%= item.quantity %>
    </div>

    <div class="metadata">
      <h4>Price</h4>
      <%= humanized_money_with_symbol(item.product.price) %>
    </div>

    <div class="metadata">
      <h4>Email</h4>
      <%= @order.email %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<!-- app/views/orders/show.html.erb -->

<section class="orders-show">

  <header class="page-header">
    <h1>Order #<%= @order.id %></h1>
  </header>

  <div class="order-summary jumbotron">
    <h4>Thank you for your order!</h4>
  </div>

  <div class="order-details">
    <% @order.line_items.each do |item| %>
      <%= render partial: 'item', locals: { item: item } %>
    <% end %>

    <div class="order-total">
      <h4>Final Amount: <%= humanized_money_with_symbol(@order.total_cents / 100.0) %></h4>
      <p>Email Used: <%= @order.email %></p>
    </div>
  </div>

  <%= link_to "Continue Shopping", root_path, class: 'btn btn-lg btn-primary' %>

</section>

app/views/products/_product.html.erb
<article class="product-card">
  <%= link_to product_path(product) do %>
    <%= image_tag product.image.thumb.url, alt: product.name %>
    <h1>
      <span><%= product.name %></span>
      <span><%= humanized_money_with_symbol product.price %></span>
    </h1>
  <% end %>
  <div>
    <% if product.quantity == 0 %>
      <div class="soldout">Sold Out</div>
      <%= button_to add_item_cart_path(product_id: product.id), class: 'btn', disabled: true do %>
        <%= fa_icon "shopping-cart", text: 'Add' %>
      <% end %>
    <% else %>
      <%= button_to add_item_cart_path(product_id: product.id), class: 'btn', method: :post do %>
        <%= fa_icon "shopping-cart", text: 'Add' %>
      <% end %>
    <% end %>
  </div>
</article>

app/views/products/index.html.erb
<section class="products-index">
  <header class="page-header">
    <div class="intro">
      <p>
        Looking for a way to add some life to your home? Look no further than our online plant shop! We have a wide variety of beautiful plants and flowers, as well as all the accessories you need to keep them healthy and happy. Plus, our prices are unbeatable! So what are you waiting for?
      </p>
      <p>
        At our online plant shop, we only sell the highest quality plants and flowers. We source our products from reputable growers and nurseries, so you can be sure you're getting a healthy, beautiful plant. Plus, ordering is quick and easy! We offer free shipping on all orders over $50, so it's easy to get the plants you want without breaking the bank.
      </p>
      <p>
        We have a wide variety of plants and flowers available for purchase on our website. Whether you're looking for something small and delicate or big and bold, we have the perfect plant for you. We also carry a selection of accessories, including potting soil, pots and containers, watering cans, and more.
      </p>
    </div>
  </header>

  <div class="products">
    <%= render @products %>
  </div>
</section>

app/views/products/show.html.erb
<section class="products-show">
  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">
    <%= image_tag @product.image.url, class: 'main-img' %>
    <div>
      <h1><%= @product.name %></h1>
      <p><%= @product.description %></p>
      <div class="quantity">
        <span><%= @product.quantity %> in stock at </span>
        <span><%= humanized_money_with_symbol @product.price %></span>
      </div>
      <div class="price">
        <% if @product.quantity == 0 %>
          <div class="sold-out-badge">Sold Out</div>
        <% else %>
          <%= button_to add_item_cart_path(product_id: @product.id), class: 'btn', method: :post do %>
            <%= fa_icon "shopping-cart", text: 'Add' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </article>
</section>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Sign Up</h1>
  </header>


  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for :user, url: '/users'  do |form| %>



        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :password %>
          <%= form.text_field :password, class: 'form-control' %>
        </div>

        <%= form.submit 'Sign Up', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>