config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'about', to: 'about#index', as: 'about'
  root to: 'products#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :users, only: [:new, :create]
  
  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  
  resources :orders, only: [:create, :show]
  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true
    validates :password, presence: true
  end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
  end
  

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: "Jungle", password: "book"
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path unless logged_in?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

  def add_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, +1)

    redirect_back fallback_location: root_path
  end

  def remove_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, -1)

    redirect_back fallback_location: root_path
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_subtotal_cents,
      description: "Khurram Virani's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end
    order.save!
    order
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    # @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
    )
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/layouts/_top_nav.html.erb
<header class="<%= current_page?(root_path) ? "hero" : "hero small" %>">
  <section class="title">
    <h3>Welcome to</h3>
    <h1>The Jungle</h1>
    <h2>Where you can find any plants!</h2>
  </section>
</header>
<nav class="navbar navbar-expand-lg navbar-dark sticky-nav">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Jungle</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          > %>
            <%# Categories %>
          <%# </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown"> %>
            <% Category.all.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, category, class: "nav-link" %>
            </li>
            <% end %>
          <%# </ul>
        </li> %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle text-danger"
            href="#"
            id="navbarDropdownAdmin"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Admin
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li><%= link_to 'Dashboard', [:admin, :root], class: "nav-link" %></li>
            <li><%= link_to 'Products', [:admin, :products], class: "nav-link" %></li>
            <li><%= link_to 'Categories', [:admin, :categories], class: "nav-link" %></li>
          </ul>
        </li>
        <li class="nav-item end-0">
          <%= link_to cart_path, class: "nav-link " do %> <%= fa_icon "shopping-cart" %>
          My Cart <%= cart.size %> <% end %>
        </li>
        <li><%= link_to 'Sign up', [:signup], class: "nav-link" %></li>
        <li><%= link_to 'Login', [:login], class: "nav-link" %></li>
        <li><%= link_to 'Logout', [:logout], class: "nav-link" %></li>
      </ul>
    </div>
  </div>
</nav>
<script>
(function(){
const gnr = () => {
    const uptitle = document.querySelector("section.title h3");
    const subtitle = document.querySelector("section.title h2");
    const header = document.querySelector("header.hero");

    uptitle.style.fontSize = "5em";
    uptitle.style.fontWeight = 900;
    uptitle.style.textAlign = "center";

    subtitle.innerHTML =
      "<p>Watch it bring you to your</p><p> shu-n-n-n-n-n-n-n-n knees, knees!</p>";
  };
  const title = document.querySelector("header.hero");
  title.addEventListener("dblclick", gnr);
  
})()
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;0,700;0,800;0,900;1,600;1,700;1,800;1,900&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top_nav' %>

  <main class="container">
    <%= yield %>
  </main>

  <%= yield :end_of_body %>

  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQ</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Help</a></li>
      <li class="nav-item"><a href="<%= about_path %>" class="nav-link px-2 text-muted">About</a></li>
      <% if logged_in? %>
        <li class="nav-item"><%= link_to 'Log Out', logout_path, method: :delete, class: 'nav-link px-2 text-muted' %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Log In', login_path, class: 'nav-link px-2 text-muted' %></li>
        <li class="nav-item"><%= link_to 'Sign Up', signup_path, class: 'nav-link px-2 text-muted' %></li>
      <% end %>
    </ul>
    <p class="text-center text-muted">© 2021 Jungle, Inc</p>
  </footer>
</body>
</html>